services:
  - type: web
    name: bookstore-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn bookstore.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        value: Mu3J_1LumQjLeLsm2VStEKvy3ESboLtkHzvheT-zvVgnvnAHOTg3eVcpEkpx2BiwGWQ
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: bookstore-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: bookstore-db
          property: connectionString
      - key: JWT_SECRET_KEY
        value: 8rxxjc9g5!l*ytye0c#9=80^j1w&v^8yu^hb!un5#+2k-&m6*#
      - key: JWT_ALGORITHM
        value: HS256
      - key: CORS_ALLOWED_ORIGINS
        value: https://bookstore-management1.netlify.app

databases:
  - name: bookstore-db
    plan: free
