# Generated by Django 5.1.7 on 2025-04-17 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatuslog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
